quarkus.application.name=Visit Polzela
quarkus.http.root-path=/

quarkus.http.host=192.168.178.87
//quarkus.http.port=${PORT:8080}

# Vaadin specific configurations
vaadin.frontend.frontend.folder=src/main/frontend
vaadin.frontend.hotdeploy=true
vaadin.whitelisted-packages=com.vaadin,org.vaadin,com.example

%prod.quarkus.package.type=uber-jar

# Static resource configuration
quarkus.http.static-resources.enabled=true
quarkus.http.static-resources.paths=META-INF/resources,META-INF/resources/frontend,src/main/frontend

# Development configuration
%dev.quarkus.package.type=fast-jar