-- V1__init_schema.sql — Source of truth for Visit Polzela database
-- Creates schema and seeds all POI data from the original flat files.

-- =============================================================================
-- DDL
-- =============================================================================

CREATE TABLE point_of_interest (
    poi_key           VARCHAR(64)  PRIMARY KEY,
    short_description VARCHAR(512),
    display_order     INT          NOT NULL DEFAULT 0,
    osm_url           VARCHAR(512),
    google_maps_url   VARCHAR(512),
    apple_maps_url    VARCHAR(512)
);

CREATE TABLE poi_translation (
    poi_key      VARCHAR(64) NOT NULL REFERENCES point_of_interest(poi_key) ON DELETE CASCADE,
    lang         VARCHAR(2)  NOT NULL,
    display_name VARCHAR(512),
    description  TEXT,
    PRIMARY KEY (poi_key, lang)
);

CREATE TABLE poi_image (
    id         BIGSERIAL   PRIMARY KEY,
    poi_key    VARCHAR(64) NOT NULL REFERENCES point_of_interest(poi_key) ON DELETE CASCADE,
    image_path VARCHAR(256) NOT NULL,
    sort_order INT          NOT NULL DEFAULT 0
);

CREATE TABLE ui_text (
    text_key VARCHAR(64) NOT NULL,
    lang     VARCHAR(2)  NOT NULL,
    value    VARCHAR(512),
    PRIMARY KEY (text_key, lang)
);

-- =============================================================================
-- SEED: Points of Interest (17 POIs, order 0-16)
-- =============================================================================

INSERT INTO point_of_interest (poi_key, short_description, display_order, osm_url, google_maps_url, apple_maps_url) VALUES
('castle',            'Historic castle in Polzela.',                                                      0,  'https://www.openstreetmap.org/node/12017530355#map=19/46.280336/15.072601', 'https://maps.app.goo.gl/jp9xW42AM45nbu2F8',  'https://maps.apple.com/?daddr=46.280336,15.072601&dirflg=d'),
('park',              'A serene park perfect for relaxation.',                                             1,  'https://www.openstreetmap.org/way/326921620#map=19/46.283478/15.074862',   'https://maps.app.goo.gl/1vjKHXKhh8Rs4gUu9',  'https://maps.apple.com/?daddr=46.283478,15.074862&dirflg=d'),
('icecream',          'Delicious local ice cream.',                                                       2,  'https://www.openstreetmap.org/#map=19/46.280175/15.076860',               'https://maps.app.goo.gl/XMrnX4wPzj7H2tzi9',  'https://maps.apple.com/?daddr=46.280175,15.076860&dirflg=d'),
('fortesa',           'Polzela''s best bakery',                                                           3,  'https://www.openstreetmap.org/#map=19/46.279552/15.077589',               'https://maps.app.goo.gl/XSEohKKe2TdmjrRd6',  'https://maps.apple.com/?daddr=46.27951710582143,15.0776195&dirflg=d'),
('mountoljka',        'Short hike to Polzela''s most visited landmark',                                   4,  'https://www.openstreetmap.org/#map=19/46.325665/15.058919',               'https://maps.app.goo.gl/XbGDZRxJdSeSL3n86',  'https://maps.apple.com/?daddr=46.325665,15.058919&dirflg=d'),
('maurerhouse',       'Birthplace of a poem writer Neža Maurer',                                          5,  'https://www.openstreetmap.org/#map=18/46.303530/15.064819',               'https://maps.app.goo.gl/Cs8csw725NywoUKUA',  'https://maps.apple.com/?daddr=46.303530,15.064819&dirflg=d'),
('romancamp',         'A signboard showing where Roman legion camp once stood',                            6,  'https://www.openstreetmap.org/#map=17/46.267967/15.094945',               'https://maps.app.goo.gl/LEhbwiPJXoZGVGdZ9',  'https://maps.apple.com/?daddr=46.267967,15.094945&dirflg=d'),
('tractormuseum',     'A nice collection of vintage tractors',                                             7,  'https://www.openstreetmap.org/#map=19/46.282075/15.074620',               'https://maps.app.goo.gl/EVyaBP29oDWiE1Uc7',  'https://maps.apple.com/?daddr=46.282075,15.074620&dirflg=d'),
('cajhnhayrack',      'Traditional Slovenian haystack',                                                    8,  'https://www.openstreetmap.org/#map=19/46.331050/15.083828',               'https://maps.app.goo.gl/DbBVhRvA5od6CKYF8',  'https://maps.apple.com/?daddr=46.321800,15.087691&dirflg=d'),
('clayfigurines',     'Funny clay figures produced by a local',                                            9,  'https://www.openstreetmap.org/#map=19/46.331050/15.083828',               'https://maps.app.goo.gl/DbBVhRvA5od6CKYF8',  'https://maps.apple.com/?daddr=46.321800,15.087691&dirflg=d'),
('noviklostermanor',  'A mysterious mannor on the outskirts of Polzela',                                  10, 'https://www.openstreetmap.org/#map=19/46.286712/15.103786',               'https://maps.app.goo.gl/tdk9kA1YPc9f64Ys6',  'https://maps.apple.com/?daddr=46.286712,15.103786&dirflg=d'),
('stmargharetachurch','Polzela''s main church',                                                           11, 'https://www.openstreetmap.org/#map=19/46.278870/15.078349',               'https://maps.app.goo.gl/faBLZwF8cnh8Teoq6',  'https://maps.apple.com/?daddr=46.278870;15.078349&dirflg=d'),
('stnicholaschurch',  'A church with a bench of love and a nice viewpoint',                               12, 'https://www.openstreetmap.org/#map=17/46.292051/15.065366',               'https://maps.app.goo.gl/nwmAGctFrEVTvaT58',  'https://maps.apple.com/?daddr=46.292051,15.065366&dirflg=d'),
('standrewchurch',    'Originally built in 1229',                                                         13, 'https://www.openstreetmap.org/#map=19/45.672306/13.825306',               'https://maps.app.goo.gl/1icHcwpuw7TuXouM7',  'https://maps.apple.com/?daddr=46.321800,15.087691&dirflg=d'),
('plaguememorial',    'Memorial of terrible plague some say victims are buried below',                     14, 'https://www.openstreetmap.org/#map=17/46.308736/15.057664',               'https://maps.app.goo.gl/zX3UpDpCv2LfQG2E7',  'https://maps.apple.com/?daddr=46.308736,15.057664&dirflg=d'),
('mesicmill',         'The most famous mill in Polzela',                                                  15, 'https://www.openstreetmap.org/node/12017530355#map=19/46.280336/15.072601','https://maps.app.goo.gl/jp9xW42AM45nbu2F8', 'https://maps.apple.com/?daddr=46.280336,15.072601&dirflg=d'),
('riverloznica',      'Local river with distinct fauna and flora',                                        16, 'https://www.openstreetmap.org/#map=16/46.27884/15.11596',                 'https://maps.app.goo.gl/pontX5isAMapiiWX7',  'https://maps.apple.com/?daddr=46.27884,15.11596&dirflg=d');

-- =============================================================================
-- SEED: POI Translations (17 POIs × 4 languages = 68 rows)
-- display_name from poititles.txt, description from poi-descriptions/*.txt
-- =============================================================================

-- castle
INSERT INTO poi_translation (poi_key, lang, display_name, description) VALUES
('castle', 'EN', 'Komenda Castle in Polzela', 'Komenda Castle, originally called Heilenstein, sits atop a hill in Polzela and has a rich history dating back to 1149. Owned by the Sovereign Military Order of Malta for centuries, it features unique elements like a marble lion and a plaque honoring poet France Prešeren. Recently renovated, the castle now serves as a cultural hub, offering spaces for events, a library, music school, and restaurant. It showcases exhibitions on the Order of Malta, poet Neža Maurer, and artist Darinka Pavletič Lorenčak, making it a significant historical and cultural landmark in the region.'),
('castle', 'SL', 'Grad Komenda v Polzeli', 'Grad Komenda, prvotno imenovan Heilenstein, stoji na hribu v Polzeli in ima bogato zgodovino, ki sega v leto 1149. Grad je bil stoletja v lasti Suverenega malteškega viteškega reda in ima edinstvene elemente, kot sta marmornati lev in plošča v čast pesniku Francetu Prešernu. Nedavno prenovljen grad zdaj služi kot kulturno središče, ki ponuja prostore za dogodke, knjižnico, glasbeno šolo in restavracijo. Prikazuje razstave o Malteškem redu, pesnici Neži Maurer in umetnici Darinki Pavletič Lorenčak, kar ga uvršča med pomembne zgodovinske in kulturne znamenitosti v regiji.'),
('castle', 'DE', 'Schloss Komenda in Polzela', 'Die Burg Komenda, ursprünglich Heilenstein genannt, liegt auf einem Hügel in Polzela und hat eine reiche Geschichte, die bis ins Jahr 1149 zurückreicht. Die Burg war jahrhundertelang im Besitz des Souveränen Malteserordens und weist einzigartige Elemente wie einen Marmorlöwen und eine Tafel zu Ehren des Dichters France Prešeren auf. Die kürzlich renovierte Burg dient heute als kulturelles Zentrum und bietet Räume für Veranstaltungen, eine Bibliothek, eine Musikschule und ein Restaurant. Sie zeigt Ausstellungen über den Malteserorden, die Dichterin Neža Maurer und die Künstlerin Darinka Pavletić Lorenčak und ist damit ein bedeutendes historisches und kulturelles Wahrzeichen der Region.'),
('castle', 'NL', 'Kasteel Komenda in Polzela', 'Het kasteel Komenda, oorspronkelijk Heilenstein genoemd, ligt op een heuvel in Polzela en heeft een rijke geschiedenis die teruggaat tot 1149. Het kasteel was eeuwenlang eigendom van de Soevereine Militaire Orde van Malta en heeft unieke elementen zoals een marmeren leeuw en een plaquette ter ere van dichter France Prešeren. Het onlangs gerenoveerde kasteel dient nu als cultureel centrum en biedt ruimtes voor evenementen, een bibliotheek, muziekschool en restaurant. Het toont tentoonstellingen over de Orde van Malta, dichteres Neža Maurer en kunstenares Darinka Pavletić Lorenčak, waardoor het een belangrijk historisch en cultureel monument in de regio is.');

-- park
INSERT INTO poi_translation (poi_key, lang, display_name, description) VALUES
('park', 'EN', 'Park Šenek', 'The manor and park are situated at a beautiful vantage point on the northern edge of Polzela. The history of Šenek dates back to the time of the Counts of Celje, as it was mentioned as a Žovneška estate as early as 1288. It acquired its Neo-Baroque appearance under its feudal owners, the Pongratz barons. Right next to the manor stands an interesting restored castle chapel dedicated to St. Florian, dating back to 1779. The manor is surrounded by the Šenek Park, which has been declared a cultural monument. Today, the park features over thirty different tree species, many of which are unusual for this region. The Polzela Municipality Tourist Association has established an Educational Trail in the park, which is worth walking along in any season. In 2022, 500 meters of walking paths were renovated and equipped with lighting, a children''s playground was installed, and a small green parking area was created. The park also provides a pleasant setting for weddings (Contact: +386 3 703 32 28, tic@polzela.si).'),
('park', 'SL', 'Park Šenek', 'Dvorec in park se nahajata na čudoviti razgledni točki na severnem robu Polzele. Zgodovina Šeneka sega v čas grofov Celjskih, saj je bil že leta 1288 omenjen kot Žovneška posest. Svoj neobaročni videz je pridobil pod svojimi fevdalnimi lastniki, baroni Pongratz. Tik ob dvorcu stoji zanimiva obnovljena grajska kapela, posvečena sv. Florijanu, ki izvira iz leta 1779. V okolici dvorca se nahaja park Šenek, ki je bil razglašen za kulturni spomenik. Danes park obsega več kot trideset različnih vrst dreves, od katerih so mnoge nenavadne za to območje. Turistično društvo Občine Polzela je v parku uredilo poučno pot, ki jo vsekakor velja prehoditi v vsakem letnem času. Leta 2022 je bilo obnovljenih 500 metrov pešpoti in opremljenih z razsvetljavo, otroško igrišče je bilo nameščeno, urejeno je bilo tudi majhno zeleno parkirišče. Park nudi tudi prijetno okolje za poroke (Kontakt: +386 3 703 32 28, tic@polzela.si).'),
('park', 'DE', 'Park Šenek', 'Das Herrenhaus und der Park befinden sich an einem schönen Aussichtspunkt am nördlichen Rand von Polzela. Die Geschichte von Šenek reicht bis in die Zeit der Grafen von Cilli zurück, da es bereits 1288 als Žovneška-Anwesen erwähnt wurde. Sein neobarockes Erscheinungsbild erhielt es unter seinen feudalen Eigentümern, den Baronen Pongratz. Direkt neben dem Herrenhaus steht eine interessante restaurierte Schlosskapelle, die dem hl. Florian gewidmet ist und aus dem Jahr 1779 stammt. Der Landsitz ist von dem Šenek-Park umgeben, der zum kulturellen Denkmal erklärt wurde. Heute gibt es im Park über dreißig verschiedene Baumarten, von denen viele für diese Region ungewöhnlich sind. Der Touristenverband der Gemeinde Polzela hat im Park einen Lehrpfad angelegt, der zu jeder Jahreszeit einen Spaziergang wert ist. Im Jahr 2022 wurden 500 Meter Wanderwege renoviert und mit Beleuchtung ausgestattet, ein Kinderspielplatz installiert und ein kleiner grüner Parkplatz angelegt. Der Park bietet auch eine angenehme Kulisse für Hochzeiten (Kontakt: +386 3 703 32 28, tic@polzela.si).'),
('park', 'NL', 'Park Šenek', 'Het landhuis en park bevinden zich op een prachtige uitkijkpunt aan de noordelijke rand van Polzela. De geschiedenis van Šenek gaat terug tot de tijd van de graven van Celje, aangezien het al in 1288 werd genoemd als Žovneška-landgoed. Het kreeg zijn neobarokke uiterlijk onder zijn feodale eigenaren, de baronnen Pongratz. Direct naast het landhuis staat een interessante gerestaureerde kasteelkapel, gewijd aan St. Florian, daterend uit 1779. Het landhuis wordt omgeven door het Šenek Park, dat is uitgeroepen tot cultureel monument. Tegenwoordig zijn er in het park meer dan dertig verschillende boomsoorten te vinden, waarvan vele ongebruikelijk zijn voor deze regio. De Toeristenvereniging van de gemeente Polzela heeft in het park een educatieve route aangelegd, die het hele jaar door een wandeling waard is. In 2022 zijn er 500 meter wandelpaden gerenoveerd en voorzien van verlichting, is er een speeltuin voor kinderen aangelegd en is er een klein groen parkeerterrein gecreëerd. Het park biedt ook een aangename omgeving voor bruiloften (Contact: +386 3 703 32 28, tic@polzela.si).');

-- icecream
INSERT INTO poi_translation (poi_key, lang, display_name, description) VALUES
('icecream', 'EN', 'Medo''s ice cream', 'Medo''s Ice Cream Bar in Polzela is a popular spot for ice cream lovers, known for its delicious flavors and friendly service. Located in the heart of the town, it offers a cozy and welcoming atmosphere for visitors of all ages. The menu features a variety of classic and unique ice cream flavors, made with high-quality ingredients. In addition to ice cream, they also serve refreshing drinks and tasty desserts, perfect for a sweet treat. The outdoor seating area provides a great place to relax and enjoy a scoop on a sunny day. Families, couples, and friends often gather here to indulge in their favorite flavors. The staff is known for their warm hospitality, making every visit a pleasant experience. Whether you''re craving a simple vanilla cone or a rich, chocolatey delight, Medo''s has something for everyone. The shop is conveniently located, making it an ideal stop while exploring Polzela. If you''re in the area, don''t miss the chance to try their famous ice cream and enjoy a delightful break.'),
('icecream', 'SL', 'Medo sladoled', 'Medov sladoledni bar v Polzeli je priljubljeno mesto za ljubitelje sladoleda, znan po svojih okusnih okusih in prijazni postrežbi. Nahaja se v središču mesta in ponuja prijetno in gostoljubno vzdušje za obiskovalce vseh starosti. Na meniju so različni klasični in edinstveni okusi sladoleda, pripravljeni iz visokokakovostnih sestavin. Poleg sladoleda strežejo tudi osvežilne pijače in okusne sladice, ki so kot nalašč za sladko razvajanje. Zunanja terasa je odličen kraj za sprostitev in uživanje ob kepici na sončen dan. Družine, pari in prijatelji se pogosto zbirajo tukaj, da uživajo v svojih najljubših okusih. Osebje je znano po svoji topli gostoljubnosti, kar vsako obiskovanje naredi prijetno izkušnjo. Ne glede na to, ali si zaželite preprost vaniljev stožec ali bogato čokoladno poslastico, Medov sladoledni bar ima nekaj za vsakogar. Trgovina je priročno locirana, kar jo naredi idealno postojanko med raziskovanjem Polzele. Če ste v bližini, ne zamudite priložnosti, da poskusite njihov slavni sladoled in uživate v prijetnem odmoru.'),
('icecream', 'DE', 'Medos Eiscreme', 'Medo''s Eisdiele in Polzela ist ein beliebter Ort für Eisliebhaber, bekannt für seine köstlichen Geschmacksrichtungen und freundlichen Service. Im Herzen der Stadt gelegen, bietet es eine gemütliche und einladende Atmosphäre für Besucher jeden Alters. Die Speisekarte bietet eine Vielzahl von klassischen und einzigartigen Eissorten, die aus hochwertigen Zutaten hergestellt werden. Neben Eis werden auch erfrischende Getränke und leckere Desserts serviert, perfekt für eine süße Leckerei. Der Außenbereich bietet einen großartigen Ort, um sich zu entspannen und an einem sonnigen Tag eine Kugel zu genießen. Familien, Paare und Freunde versammeln sich oft hier, um ihre Lieblingsgeschmacksrichtungen zu genießen. Das Personal ist bekannt für seine herzliche Gastfreundschaft, die jeden Besuch zu einem angenehmen Erlebnis macht. Egal, ob Sie Lust auf eine einfache Vanillewaffel oder eine reichhaltige, schokoladige Köstlichkeit haben, Medo''s hat für jeden etwas. Der Laden ist günstig gelegen und damit ein idealer Zwischenstopp beim Erkunden von Polzela. Wenn Sie in der Gegend sind, verpassen Sie nicht die Gelegenheit, ihr berühmtes Eis zu probieren und eine angenehme Pause zu genießen.'),
('icecream', 'NL', 'Medo''s IJs', 'Medo''s IJssalon in Polzela is een populaire plek voor ijsliefhebbers, bekend om zijn heerlijke smaken en vriendelijke service. Gelegen in het hart van de stad, biedt het een gezellige en gastvrije sfeer voor bezoekers van alle leeftijden. Het menu biedt een verscheidenheid aan klassieke en unieke ijssmaken, gemaakt met hoogwaardige ingrediënten. Naast ijs serveren ze ook verfrissende drankjes en smakelijke desserts, perfect voor een zoete traktatie. Het buitenterras biedt een geweldige plek om te ontspannen en te genieten van een bolletje op een zonnige dag. Gezinnen, stellen en vrienden komen hier vaak samen om te genieten van hun favoriete smaken. Het personeel staat bekend om zijn warme gastvrijheid, waardoor elk bezoek een aangename ervaring wordt. Of je nu zin hebt in een eenvoudige vanillekegel of een rijke, chocoladesensatie, Medo''s heeft voor ieder wat wils. De winkel is gunstig gelegen, waardoor het een ideale stop is tijdens het verkennen van Polzela. Als je in de buurt bent, mis dan niet de kans om hun beroemde ijs te proberen en te genieten van een heerlijke pauze.');

-- fortesa
INSERT INTO poi_translation (poi_key, lang, display_name, description) VALUES
('fortesa', 'EN', 'Fortesa Bakery', 'Fortesa Bakery is a local spot in Polzela known for freshly baked bread and everyday treats. Stop by for warm croissants, pizza slices, burek, gibanica and other pastries—perfect for breakfast, a quick snack, or something sweet to take away.'),
('fortesa', 'SL', 'Pekarna Fortesa', 'Pekarna Fortesa v Polzeli slovi po sveže pečenem kruhu in vsakodnevnih dobrotah. Ustavite se po še topel rogljiček, kos pice, burek, gibanico in drugo pecivo—idealno za zajtrk, hitro malico ali sladek prigrizek za s seboj.'),
('fortesa', 'DE', 'Bäckerei Fortesa', 'Die Bäckerei Fortesa in Polzela ist für frisches Brot und tägliche Leckereien bekannt. Holen Sie sich warme Croissants, Pizzastücke, Burek, Gibanica und anderes Gebäck—perfekt zum Frühstück, für einen schnellen Snack oder etwas Süßes zum Mitnehmen.'),
('fortesa', 'NL', 'Bakkerij Fortesa', 'Bakkerij Fortesa in Polzela staat bekend om vers gebakken brood en lekkernijen voor elke dag. Kom langs voor warme croissants, een stuk pizza, burek, gibanica en ander gebak—ideaal als ontbijt, snelle snack of iets zoets om mee te nemen.');

-- mountoljka
INSERT INTO poi_translation (poi_key, lang, display_name, description) VALUES
('mountoljka', 'EN', 'Mount Oljka and the Mountaineering Lodge', 'Gora Oljka (734 m) was mentioned as early as 1243 as "Križna gora" (Cross Mountain). From a contract between the owner from Šoštanj and the Order of Malta, it is evident that since at least the mid-17th century, a large cross and a chapel with statues of St. Judoc (Sv. Jošt) and St. Agnes (Sv. Neža) stood on the mountain. The present church was built between 1754 and 1757. The main altar, which ranks the church on Gora Oljka among the most impressive monuments, is notable. It is the work of sculptor Ferdinand Gallo. His sense of theatrical effects reached its peak in the Last Supper on the large altar. The row of seated apostles, life-sized, who express their emotions with vivid gestures during the Last Supper, has left the usual altar setting and seeks direct contact with the viewer. On the upper part of the altar is a painting by Fortunat Bergant, "Christ in the Garden of Gethsemane." Above it is a large cross, beneath it a statue of the Sorrowful Mother of God, with statues of St. Agnes and St. Judoc on either side. Below the church is an underground shrine with the Holy Sepulchre. The church facade and all stone parts were renovated in 1998, as well as the external lighting. Next to the church stands a well-maintained and renovated mountain lodge with approximately 150 seats and 50 beds. Access is possible from Polzela (2 hours), Šmartno ob Paki (1.5 hours), Rečica (2 hours), Velenje (3 hours), Šoštanj (2.5 hours), Skorno (2 hours), Paška vas (1.5 hours), and Andraž. Access is also possible by bus from Polzela.'),
('mountoljka', 'SL', 'Oljka in planinska koča', 'Gora Oljka (734 m) je bila omenjena že leta 1243 kot "Križna gora". Iz pogodbe med lastnikom iz Šoštanja in Malteškim redom je razvidno, da sta na gori vsaj od sredine 17. stoletja stala velik križ in kapela s kipoma sv. Jošta in sv. Neže. Sedanjo cerkev so zgradili med letoma 1754 in 1757. Glavni oltar, ki cerkev na Gori Oljki uvršča med najbolj impresivne spomenike, je izjemen. Je delo kiparja Ferdinanda Galla. Njegov občutek za gledališke učinke je dosegel vrhunec pri Zadnji večerji na velikem oltarju. Vrsta sedečih apostolov v naravni velikosti, ki z živahnimi gestami izražajo svoja čustva med Zadnjo večerjo, je zapustila običajno oltarno postavitev in išče neposreden stik z gledalcem. Na zgornjem delu oltarja je slika Fortunata Berganta "Kristus v vrtu Getsemani". Nad njo je velik križ, pod njim kip Žalostne Matere Božje, ob straneh pa kipa sv. Neže in sv. Jošta. Pod cerkvijo je podzemna kapela s Svetim grobom. Fasada cerkve in vsi kamniti deli so bili obnovljeni leta 1998, prav tako zunanja razsvetljava.'),
('mountoljka', 'DE', 'Oljka und die Berghütte', 'Gora Oljka (734 m) wurde bereits 1243 als "Križna gora" (Kreuzberg) erwähnt. Aus einem Vertrag zwischen dem Besitzer aus Šoštanj und dem Malteserorden geht hervor, dass seit mindestens der Mitte des 17. Jahrhunderts ein großes Kreuz und eine Kapelle mit Statuen von St. Judoc (Sv. Jošt) und St. Agnes (Sv. Neža) auf dem Berg standen. Die heutige Kirche wurde zwischen 1754 und 1757 erbaut. Der Hauptaltar, der die Kirche auf Gora Oljka zu den beeindruckendsten Denkmälern zählt, ist bemerkenswert. Es ist das Werk des Bildhauers Ferdinand Gallo. Sein Sinn für theatralische Effekte erreichte seinen Höhepunkt beim Abendmahl am großen Altar. Die Reihe der sitzenden Apostel in Lebensgröße, die ihre Emotionen mit lebhaften Gesten während des Abendmahls ausdrücken, hat die übliche Altaranordnung verlassen und sucht direkten Kontakt mit dem Betrachter. Im oberen Teil des Altars befindet sich ein Gemälde von Fortunat Bergant, "Christus im Garten von Gethsemane". Darüber befindet sich ein großes Kreuz, darunter eine Statue der Schmerzensmutter Gottes, mit Statuen von St. Agnes und St. Judoc auf beiden Seiten. Unter der Kirche befindet sich eine unterirdische Kapelle mit dem Heiligen Grab. Die Kirchenfassade und alle Steinteile wurden 1998 renoviert, ebenso die Außenbeleuchtung.'),
('mountoljka', 'NL', 'Mount Oljka en de Berghut', 'Gora Oljka (734 m) werd al in 1243 genoemd als "Križna gora" (Kruisberg). Uit een contract tussen de eigenaar uit Šoštanj en de Orde van Malta blijkt dat sinds minstens het midden van de 17e eeuw een groot kruis en een kapel met beelden van St. Judoc (Sv. Jošt) en St. Agnes (Sv. Neža) op de berg stonden. De huidige kerk werd gebouwd tussen 1754 en 1757. Het hoofdaltaar, dat de kerk op Gora Oljka tot een van de meest indrukwekkende monumenten maakt, is opmerkelijk. Het is het werk van beeldhouwer Ferdinand Gallo. Zijn gevoel voor theatrale effecten bereikte zijn hoogtepunt in het Laatste Avondmaal op het grote altaar. De rij zittende apostelen, levensgroot, die hun emoties met levendige gebaren uitdrukken tijdens het Laatste Avondmaal, heeft de gebruikelijke altaaropstelling verlaten en zoekt direct contact met de kijker. Op het bovenste deel van het altaar bevindt zich een schilderij van Fortunat Bergant, "Christus in de Hof van Getsemane". Daarboven bevindt zich een groot kruis, daaronder een beeld van de Moeder Gods van Smarten, met beelden van St. Agnes en St. Judoc aan weerszijden. Onder de kerk bevindt zich een ondergrondse kapel met het Heilig Graf. De kerkgevel en alle stenen delen werden in 1998 gerenoveerd, evenals de buitenverlichting.');

-- maurerhouse
INSERT INTO poi_translation (poi_key, lang, display_name, description) VALUES
('maurerhouse', 'EN', 'Neža Maurer''s Birthplace', 'In the settlement of Kopank in Podvin near Polzela stands the birthplace of Neža Maurer, a renowned Slovenian poet, writer, publicist, and honorary citizen of the Municipality of Polzela. The house was fully restored in 2022 and is one of the few preserved in its immediate and distant surroundings, telling the story of the way of life, farming, and living in the past. Neža Maurer''s house is considered a cultural monument of local importance with the characteristics of an ethnological monument and invites visitors to take a tour. Under the nearby hayrack, benches have been set up for rest, along with a bookshelf that invites visitors to read and exchange books. Visits must be arranged in advance by calling 03 703 32 28 or emailing tic@polzela.si.'),
('maurerhouse', 'SL', 'Rojstna hiša Neže Maurer', 'V naselju Kopank v Podvinu pri Polzeli stoji rojstna hiša Neže Maurer, priznane slovenske pesnice, pisateljice, publicistke in častne občanke Občine Polzela. Hiša je bila popolnoma obnovljena leta 2022 in je ena redkih ohranjenih v svoji neposredni in daljni okolici, ki pripoveduje zgodbo o načinu življenja, kmetovanju in bivanju v preteklosti. Hiša Neže Maurer velja za kulturni spomenik lokalnega pomena z značilnostmi etnološkega spomenika in vabi obiskovalce na ogled. Pod bližnjim kozolcem so postavili klopi za počitek, skupaj s knjižno polico, ki vabi obiskovalce k branju in izmenjavi knjig. Obiske je potrebno vnaprej dogovoriti na telefonu 03 703 32 28 ali po elektronski pošti tic@polzela.si.'),
('maurerhouse', 'DE', 'Neža Maurers Geburtsort', 'In der Siedlung Kopank in Podvin bei Polzela steht das Geburtshaus von Neža Maurer, einer renommierten slowenischen Dichterin, Schriftstellerin, Publizistin und Ehrenbürgerin der Gemeinde Polzela. Das Haus wurde 2022 vollständig restauriert und ist eines der wenigen erhaltenen in seiner unmittelbaren und ferneren Umgebung, das die Geschichte der Lebensweise, Landwirtschaft und des Lebens in der Vergangenheit erzählt. Neža Maurers Haus gilt als Kulturdenkmal von örtlicher Bedeutung mit den Merkmalen eines ethnologischen Denkmals und lädt Besucher zu einer Besichtigung ein. Unter dem nahe gelegenen Heustadel wurden Bänke zum Ausruhen aufgestellt, zusammen mit einem Bücherregal, das Besucher zum Lesen und Austauschen von Büchern einlädt. Besuche müssen im Voraus vereinbart werden, indem Sie 03 703 32 28 anrufen oder tic@polzela.si per E-Mail kontaktieren.'),
('maurerhouse', 'NL', 'Neža Maurers Geboortehuis', 'In de nederzetting Kopank in Podvin bij Polzela staat het geboortehuis van Neža Maurer, een gerenommeerde Sloveense dichteres, schrijfster, publiciste en ereburger van de gemeente Polzela. Het huis werd in 2022 volledig gerestaureerd en is een van de weinige bewaard gebleven in zijn directe en verdere omgeving, die het verhaal vertelt van de levenswijze, landbouw en het leven in het verleden. Neža Maurers huis wordt beschouwd als een cultureel monument van lokaal belang met de kenmerken van een etnologisch monument en nodigt bezoekers uit voor een rondleiding. Onder de nabijgelegen hooischuur zijn banken geplaatst om uit te rusten, samen met een boekenkast die bezoekers uitnodigt om te lezen en boeken uit te wisselen. Bezoeken moeten van tevoren worden afgesproken door te bellen naar 03 703 32 28 of door te e-mailen naar tic@polzela.si.');

-- romancamp
INSERT INTO poi_translation (poi_key, lang, display_name, description) VALUES
('romancamp', 'EN', 'Roman Legionary Camp', 'The military camp in Ločica ob Savinji was established at the end of the 60s of the 2nd century for the needs of the II Italian Legion, which consisted of 5,500 legionaries. Its task was to ensure the security of the Roman Empire on its eastern border. The military camp complex was designed in the shape of a regular rectangle measuring 543 x 435 meters, with walls and towers, within which the necessary infrastructure was built – roads, canals, and buildings – including the headquarters and military barracks.'),
('romancamp', 'SL', 'Rimski legijski tabor', 'Vojaški tabor v Ločici ob Savinji je bil ustanovljen konec 60. let 2. stoletja za potrebe II italijanske legije, ki je štela 5.500 legionarjev. Njegova naloga je bila zagotavljanje varnosti Rimskega imperija na njegovi vzhodni meji. Kompleks vojaškega tabora je bil zasnovan v obliki pravilnega pravokotnika, ki meri 543 x 435 metrov, z zidovi in stolpi, znotraj katerih je bila zgrajena potrebna infrastruktura – ceste, kanali in stavbe – vključno s poveljstvom in vojaškimi barakami.'),
('romancamp', 'DE', 'Römisches Legionärslager', 'Das Militärlager in Ločica ob Savinji wurde Ende der 60er Jahre des 2. Jahrhunderts für die Bedürfnisse der II italienischen Legion gegründet, die aus 5.500 Legionären bestand. Seine Aufgabe war es, die Sicherheit des Römischen Reiches an seiner östlichen Grenze zu gewährleisten. Der Militärlagerkomplex wurde in Form eines regelmäßigen Rechtecks mit den Maßen 543 x 435 Meter entworfen, mit Mauern und Türmen, innerhalb derer die notwendige Infrastruktur gebaut wurde – Straßen, Kanäle und Gebäude – einschließlich des Hauptquartiers und der Militärbaracken.'),
('romancamp', 'NL', 'Romeins Legioenkamp', 'Het militaire kamp in Ločica ob Savinji werd eind jaren 60 van de 2e eeuw opgericht voor de behoeften van het II Italiaanse Legioen, dat bestond uit 5.500 legionairs. Zijn taak was om de veiligheid van het Romeinse Rijk aan zijn oostelijke grens te waarborgen. Het militaire kampcomplex werd ontworpen in de vorm van een regelmatige rechthoek van 543 x 435 meter, met muren en torens, binnen waarvan de nodige infrastructuur werd gebouwd – wegen, kanalen en gebouwen – inclusief het hoofdkwartier en militaire barakken.');

-- tractormuseum
INSERT INTO poi_translation (poi_key, lang, display_name, description) VALUES
('tractormuseum', 'EN', 'Museum of Vintage Tractors', 'A unique collection of more than twenty vintage cars, gathered by the owner Ernest Obermayer from various parts of Slovenia and Austria, all of which he restored to the point where they are in full working condition. Part of the collection is a 1952 Mercedes-Benz with a wooden chassis under the metal body, of which he is particularly proud. The latest addition to the museum is a Fordson from 1919, the oldest tractor in this part of Europe. Visits must be arranged in advance by calling 03 703 32 28 or emailing tic@polzela.si.'),
('tractormuseum', 'SL', 'Muzej starodobnih traktorjev', 'Edinstvena zbirka več kot dvajsetih starodobnih avtomobilov, ki jih je lastnik Ernest Obermayer zbral iz različnih delov Slovenije in Avstrije ter jih obnovil do popolne delovne kondicije. Del zbirke je Mercedes-Benz iz leta 1952 z lesenim podvozjem pod kovinskim ohišjem, na katerega je še posebej ponosen. Zadnja pridobitev muzeja je Fordson iz leta 1919, najstarejši traktor v tem delu Evrope. Obisk je treba predhodno dogovoriti na telefonski številki 03 703 32 28 ali po e-pošti tic@polzela.si.'),
('tractormuseum', 'DE', 'Museum für Oldtimer-Traktoren', 'Eine einzigartige Sammlung von mehr als zwanzig Oldtimern, die der Besitzer Ernest Obermayer aus verschiedenen Teilen Sloweniens und Österreichs zusammengetragen und so restauriert hat, dass sie voll funktionsfähig sind. Teil der Sammlung ist ein Mercedes-Benz von 1952 mit einem Holzrahmen unter der Metallkarosserie, auf den er besonders stolz ist. Die neueste Ergänzung des Museums ist ein Fordson von 1919, der älteste Traktor in diesem Teil Europas. Besuche müssen im Voraus telefonisch unter 03 703 32 28 oder per E-Mail an tic@polzela.si vereinbart werden.'),
('tractormuseum', 'NL', 'Oldtimer Tractor Museum', 'Een unieke collectie van meer dan twintig oldtimers, verzameld door de eigenaar Ernest Obermayer uit verschillende delen van Slovenië en Oostenrijk, die hij allemaal heeft gerestaureerd tot ze volledig operationeel zijn. Een onderdeel van de collectie is een Mercedes-Benz uit 1952 met een houten chassis onder de metalen carrosserie, waar hij bijzonder trots op is. De nieuwste toevoeging aan het museum is een Fordson uit 1919, de oudste tractor in dit deel van Europa. Bezoeken moeten vooraf worden geregeld door te bellen naar 03 703 32 28 of een e-mail te sturen naar tic@polzela.si.');

-- cajhnhayrack
INSERT INTO poi_translation (poi_key, lang, display_name, description) VALUES
('cajhnhayrack', 'EN', 'Cajhn''s Hayrack', 'It represents a small ethnological collection. On the restored facade, old farming tools and implements are displayed, which in the past made many farm tasks easier. The proud owner, Štefka Cajhen, has been collecting tools since 1991, with many of them coming from her family farm. Visits must be arranged in advance by calling 03 703 32 28 or emailing tic@polzela.si.'),
('cajhnhayrack', 'SL', 'Cajhnova kozolec', 'Predstavlja majhno etnološko zbirko. Na obnovljeni fasadi so razstavljena stara kmečka orodja in pripomočki, ki so v preteklosti olajšali številna kmečka opravila. Ponosna lastnica, Štefka Cajhen, zbira orodja od leta 1991, pri čemer jih je veliko iz njene družinske kmetije. Obisk je treba predhodno dogovoriti na telefonski številki 03 703 32 28 ali po e-pošti tic@polzela.si.'),
('cajhnhayrack', 'DE', 'Cajhns Heuhaufen', 'Es stellt eine kleine ethnologische Sammlung dar. An der restaurierten Fassade sind alte landwirtschaftliche Werkzeuge und Geräte ausgestellt, die in der Vergangenheit viele landwirtschaftliche Aufgaben erleichtert haben. Die stolze Besitzerin, Štefka Cajhen, sammelt seit 1991 Werkzeuge, von denen viele von ihrem Familienhof stammen. Besuche müssen im Voraus unter der Telefonnummer 03 703 32 28 oder per E-Mail an tic@polzela.si vereinbart werden.'),
('cajhnhayrack', 'NL', 'Cajhns Hooiberg', 'Het vertegenwoordigt een kleine etnologische collectie. Op de gerestaureerde gevel worden oude landbouwgereedschappen en werktuigen tentoongesteld, die in het verleden veel boerderijtaken gemakkelijker maakten. De trotse eigenaar, Štefka Cajhen, verzamelt sinds 1991 gereedschappen, waarvan vele afkomstig zijn van haar familieboerderij. Bezoeken moeten vooraf worden geregeld door te bellen naar 03 703 32 28 of een e-mail te sturen naar tic@polzela.si.');

-- clayfigurines
INSERT INTO poi_translation (poi_key, lang, display_name, description) VALUES
('clayfigurines', 'EN', 'Whimsical Clay Figurines', 'Since 2007, in Andraž nad Polzelo, a permanent exhibition of the collection Humorous Clay Figurines by Miran Čobal has been on display. It humorously depicts literary characters (such as Švejk, Martin Krpan, the Butalci…) and scenes from village life (musicians, teachers, etc.) set in miniature environments with detailed features that attract the visitor''s eye. Visits must be arranged in advance by calling 03 703 32 28 or emailing tic@polzela.si.'),
('clayfigurines', 'SL', 'Humoristične glinene figurice', 'Od leta 2007 je v Andražu nad Polzelo na ogled stalna razstava zbirke Humorne glinene figurice Mirana Čobala. Zbirka na humoren način prikazuje literarne like (kot so Švejk, Martin Krpan, Butalci ...) in prizore iz vaškega življenja (glasbeniki, učitelji itd.), postavljene v miniaturna okolja z detajli, ki pritegnejo obiskovalčevo oko. Obisk je treba predhodno dogovoriti na telefonski številki 03 703 32 28 ali po e-pošti tic@polzela.si.'),
('clayfigurines', 'DE', 'Witzige Tonfiguren', 'Seit 2007 ist in Andraž nad Polzelo eine Dauerausstellung der Sammlung Humorvolle Tonfiguren von Miran Čobal zu sehen. Die Sammlung zeigt auf humorvolle Weise literarische Figuren (wie Švejk, Martin Krpan, die Butalci ...) und Szenen aus dem Dorfleben (Musiker, Lehrer usw.), die in Miniaturumgebungen mit Details dargestellt sind, die das Auge des Besuchers anziehen. Besuche müssen im Voraus unter der Telefonnummer 03 703 32 28 oder per E-Mail an tic@polzela.si vereinbart werden.'),
('clayfigurines', 'NL', 'Grappige Klei Figuren', 'Sinds 2007 is in Andraž nad Polzelo een permanente tentoonstelling van de collectie Humoristische Kleifiguren van Miran Čobal te zien. De collectie toont op humoristische wijze literaire personages (zoals Švejk, Martin Krpan, de Butalci ...) en scènes uit het dorpsleven (muzikanten, leraren, enz.) in miniatuuromgevingen met details die de aandacht van de bezoeker trekken. Bezoeken moeten vooraf worden geregeld door te bellen naar 03 703 32 28 of een e-mail te sturen naar tic@polzela.si.');

-- noviklostermanor
INSERT INTO poi_translation (poi_key, lang, display_name, description) VALUES
('noviklostermanor', 'EN', 'Novi Klošter Manor', 'The monastery in Založe was built by Count Frederick II of Celje and was gifted to Dominican monks in 1453. It was dissolved at the end of the 18th century by Emperor Joseph II. It was twice ravaged by the Turks and later rebuilt into a manor, with the surrounding area transformed into a park where various trees were planted. During World War II, many trees were cut down by the Germans, but some important ones remain. The last owner before World War II was Oto Parin. His son, Paul Parin, a doctor, surgeon, neurologist, and psychoanalyst who lived in Switzerland, published over 50 scientific papers and also wrote a literary work titled Reliable Signs of Change, which has been translated and, among other things, describes his youth at Novo Klošter and the cultural and historical significance of the manor. The manor was also the site of the first elementary school in Polzela. In 1786, a so-called trivial school was established in Novo Klošter. In 1796, the school moved to Polzela.'),
('noviklostermanor', 'SL', 'Novi Klošter', 'Samostan v Založah je zgradil grof Friderik II Celjski in ga leta 1453 podaril dominikanskim menihom. Razpuščen je bil konec 18. stoletja s strani cesarja Jožefa II. Dvakrat so ga opustošili Turki, kasneje pa je bil obnovljen v dvorec, okoliški prostor pa je bil preoblikovan v park, kjer so posadili različna drevesa. Med drugo svetovno vojno so Nemci posekali veliko dreves, vendar so nekatera pomembna ostala. Zadnji lastnik pred drugo svetovno vojno je bil Oto Parin. Njegov sin, Paul Parin, zdravnik, kirurg, nevrolog in psihoanalitik, ki je živel v Švici, je objavil več kot 50 znanstvenih člankov in napisal tudi literarno delo z naslovom Zanesljivi znaki sprememb, ki je bilo prevedeno in med drugim opisuje njegovo mladost v Novem Kloštru ter kulturni in zgodovinski pomen dvorca. Dvorec je bil tudi mesto prve osnovne šole v Polzeli. Leta 1786 je bila v Novem Kloštru ustanovljena tako imenovana trivialna šola. Leta 1796 se je šola preselila v Polzelo.'),
('noviklostermanor', 'DE', 'Novi Klošter', 'Das Kloster in Založe wurde von Graf Friedrich II. von Cilli erbaut und 1453 den Dominikanermönchen geschenkt. Es wurde Ende des 18. Jahrhunderts von Kaiser Joseph II. aufgelöst. Es wurde zweimal von den Türken verwüstet und später in ein Herrenhaus umgebaut, wobei das umliegende Gebiet in einen Park umgewandelt wurde, in dem verschiedene Bäume gepflanzt wurden. Während des Zweiten Weltkriegs wurden viele Bäume von den Deutschen gefällt, aber einige wichtige blieben erhalten. Der letzte Besitzer vor dem Zweiten Weltkrieg war Oto Parin. Sein Sohn, Paul Parin, Arzt, Chirurg, Neurologe und Psychoanalytiker, der in der Schweiz lebte, veröffentlichte über 50 wissenschaftliche Arbeiten und schrieb auch ein literarisches Werk mit dem Titel Zuverlässige Zeichen des Wandels, das übersetzt wurde und unter anderem seine Jugend in Novo Klošter sowie die kulturelle und historische Bedeutung des Herrenhauses beschreibt. Das Herrenhaus war auch der Standort der ersten Grundschule in Polzela. Im Jahr 1786 wurde in Novo Klošter eine sogenannte triviale Schule gegründet. 1796 zog die Schule nach Polzela um.'),
('noviklostermanor', 'NL', 'Novi Klošter', 'Het klooster in Založe werd gebouwd door graaf Frederik II van Celje en werd in 1453 geschonken aan de Dominicaner monniken. Het werd aan het einde van de 18e eeuw ontbonden door keizer Jozef II. Het werd tweemaal verwoest door de Turken en later herbouwd tot een landhuis, waarbij het omliggende gebied werd omgevormd tot een park waar verschillende bomen werden geplant. Tijdens de Tweede Wereldoorlog werden veel bomen door de Duitsers gekapt, maar enkele belangrijke bleven behouden. De laatste eigenaar voor de Tweede Wereldoorlog was Oto Parin. Zijn zoon, Paul Parin, arts, chirurg, neuroloog en psychoanalyticus, die in Zwitserland woonde, publiceerde meer dan 50 wetenschappelijke artikelen en schreef ook een literair werk getiteld Betrouwbare Tekenen van Verandering, dat werd vertaald en onder andere zijn jeugd in Novo Klošter en de culturele en historische betekenis van het landhuis beschrijft. Het landhuis was ook de locatie van de eerste basisschool in Polzela. In 1786 werd in Novo Klošter een zogenaamde triviale school opgericht. In 1796 verhuisde de school naar Polzela.');

-- stmargharetachurch (EN description spans 2 paragraphs in source file)
INSERT INTO poi_translation (poi_key, lang, display_name, description) VALUES
('stmargharetachurch', 'EN', 'Church of St. Margaret', 'The Parish Church of St. Margaret was built not far from Heilenstein Castle, in the present-day center of Polzela, and is first mentioned in 1255. The owners of Heilenstein Castle expanded their estates in connection with the estates of the Counts of Celje. The original church was Romanesque. In 1263, it became a commandery church, as evidenced by the Maltese cross relief on the ceiling in the presbytery. Over the centuries, the church was renovated several times, most significantly in 1616 when it took on its current form. The Romanesque building was baroque-ized, and the present presbytery, both chapels, and the sacristy were added; the bell tower was raised by one floor, though it retained its Gothic design. An interesting feature of the church is the relic of St. Theodore, which was brought from Rome for the church by Commander Helfenthal. The glass coffin, in which the body of St. Theodore lay on red velvet, dressed in a precious garment decorated with gold and silver, was initially kept in the church on Gora Oljka. When a decree was issued in 1788, during the Josephine reforms, ordering the closure of the church, the relics of St. Theodore were transferred to Polzela.'),
('stmargharetachurch', 'SL', 'Cerkev sv. Margarete', 'Župnijska cerkev sv. Marjete je bila zgrajena nedaleč od gradu Heilenstein, v današnjem središču Polzele, in je prvič omenjena leta 1255. Lastniki gradu Heilenstein so razširili svoja posestva v povezavi s posestvi grofov Celjskih. Prvotna cerkev je bila romanska. Leta 1263 je postala komendatorska cerkev, kar dokazuje relief malteškega križa na stropu v prezbiteriju. Cerkev je bila skozi stoletja večkrat prenovljena, najbolj pomembno leta 1616, ko je dobila sedanjo podobo. Romanska stavba je bila barokizirana, dodani so bili sedanji prezbiterij, obe kapeli in zakristija; zvonik je bil dvignjen za eno nadstropje, čeprav je ohranil svojo gotsko zasnovo.'),
('stmargharetachurch', 'DE', 'Kirche St. Margarete', 'Die Pfarrkirche St. Margareta wurde unweit der Burg Heilenstein im heutigen Zentrum von Polzela erbaut und erstmals 1255 erwähnt. Die Besitzer der Burg Heilenstein erweiterten ihre Besitztümer in Verbindung mit den Besitztümern der Grafen von Cilli. Die ursprüngliche Kirche war romanisch. Im Jahr 1263 wurde sie zur Kommandantenkirche, wie das Relief des Malteserkreuzes an der Decke im Presbyterium belegt. Im Laufe der Jahrhunderte wurde die Kirche mehrfach renoviert, am bedeutendsten im Jahr 1616, als sie ihre heutige Form annahm. Das romanische Gebäude wurde barockisiert, und der heutige Presbyterium, beide Kapellen und die Sakristei wurden hinzugefügt; der Glockenturm wurde um eine Etage erhöht, behielt jedoch sein gotisches Design.'),
('stmargharetachurch', 'NL', 'Kerk van St. Margareta', 'De parochiekerk van St. Margaretha werd gebouwd niet ver van het kasteel Heilenstein, in het huidige centrum van Polzela, en wordt voor het eerst genoemd in 1255. De eigenaren van kasteel Heilenstein breidden hun landgoederen uit in verband met de landgoederen van de graven van Celje. De oorspronkelijke kerk was romaans. In 1263 werd het een commanderijkerk, zoals blijkt uit het reliëf van het Maltezer kruis op het plafond in het priesterkoor. Door de eeuwen heen werd de kerk meerdere keren gerenoveerd, het meest significant in 1616 toen het zijn huidige vorm kreeg. Het romaanse gebouw werd barok gemaakt, en het huidige priesterkoor, beide kapellen en de sacristie werden toegevoegd; de klokkentoren werd met één verdieping verhoogd, hoewel het zijn gotische ontwerp behield.');

-- stnicholaschurch
INSERT INTO poi_translation (poi_key, lang, display_name, description) VALUES
('stnicholaschurch', 'EN', 'Church of St. Nicholas in Vimperk', 'The church is first mentioned in the Strasbourg visitation protocol from 1545, but its origins are older, likely dating to the second half of the 14th century. It underwent Baroque renovation during the time of Commander Baron Gloyach. In 1728, the church received its current vault, replacing the original Gothic wooden ceiling, and in the following decades, a sacristy and bell tower were added. The main altar bears the year 1783. The organ in the choir loft was brought from Gora Oljka in 1857. The bell tower was renovated in 1850, and during another renovation in 1994, it was raised by 70 cm, restoring its original shape.'),
('stnicholaschurch', 'SL', 'Cerkev sv. Nikolaja v Vimperku', 'Cerkev je prvič omenjena v Strasbourškem vizitacijskem protokolu iz leta 1545, vendar so njeni začetki starejši, verjetno segajo v drugo polovico 14. stoletja. Doživela je baročno prenovo v času poveljnika barona Gloyacha. Leta 1728 je cerkev dobila sedanje oboke, ki so nadomestili prvotne gotske lesene strope, v naslednjih desetletjih pa so dodali zakristijo in zvonik. Glavni oltar nosi letnico 1783. Organe na pevskem koru so leta 1857 prinesli z Gore Oljke. Zvonik je bil prenovljen leta 1850, med drugo prenovo leta 1994 pa je bil dvignjen za 70 cm, s čimer je bila obnovljena njegova prvotna oblika.'),
('stnicholaschurch', 'DE', 'Kirche St. Nikolaus in Vimperk', 'Die Kirche wird erstmals im Straßburger Visitationsprotokoll von 1545 erwähnt, ihre Ursprünge sind jedoch älter und stammen wahrscheinlich aus der zweiten Hälfte des 14. Jahrhunderts. Sie wurde während der Zeit des Kommandanten Baron Gloyach barock renoviert. Im Jahr 1728 erhielt die Kirche ihr heutiges Gewölbe, das die ursprüngliche gotische Holzdecke ersetzte, und in den folgenden Jahrzehnten wurden eine Sakristei und ein Glockenturm hinzugefügt. Der Hauptaltar trägt die Jahreszahl 1783. Die Orgel auf der Empore wurde 1857 von Gora Oljka gebracht. Der Glockenturm wurde 1850 renoviert, und bei einer weiteren Renovierung im Jahr 1994 wurde er um 70 cm erhöht, wodurch seine ursprüngliche Form wiederhergestellt wurde.'),
('stnicholaschurch', 'NL', 'Kerk van St. Nikolaas in Vimperk', 'De kerk wordt voor het eerst genoemd in het Straatsburgse visitatieprotocol uit 1545, maar de oorsprong is ouder, waarschijnlijk daterend uit de tweede helft van de 14e eeuw. Het onderging een barokke renovatie tijdens de tijd van commandant Baron Gloyach. In 1728 kreeg de kerk haar huidige gewelf, ter vervanging van het oorspronkelijke gotische houten plafond, en in de daaropvolgende decennia werden een sacristie en klokkentoren toegevoegd. Het hoofdaltaar draagt het jaartal 1783. Het orgel in de koorruimte werd in 1857 vanuit Gora Oljka gebracht. De klokkentoren werd in 1850 gerenoveerd en tijdens een andere renovatie in 1994 werd hij met 70 cm verhoogd, waardoor zijn oorspronkelijke vorm werd hersteld.');

-- standrewchurch (source file has all langs concatenated in EN line; SL/DE/NL extracted)
INSERT INTO poi_translation (poi_key, lang, display_name, description) VALUES
('standrewchurch', 'EN', 'Church of St. Andrew', 'Once a picturesque little church, first mentioned in a document from 1229, it has since become a magnificent parish church offering a scenic view of the entire area of Andraž nad Polzelo. The origins of this church are connected to the local landowners of Polzela and the Counts of Celje. Frederick I managed the Upper Carniolan Monastery, which held estates near St. Andrew and Dobrič. The Church of St. Andrew was initially a larger chapel, built in the Romanesque style. No remains or visible signs of this chapel exist today. In the second half of the 15th century, the chapel was rebuilt and expanded in the Gothic style. Remnants from this period are still visible today, with the most interesting being the Gothic stone portal, which featured two coats of arms: the Maltese cross on the right and the coat of arms of the Counts of Celje with three stars on the left. This symbol indicates that the Counts of Celje and the commanders of Polzela had patronage over the church. Since 1545, it has been mentioned as a branch of the Polzela parish. The current church includes the presbytery, nave, and two side chapels that give it the shape of a cross. It underwent major renovation in the second half of the 19th century, when new altars were installed: the main altar, two larger, and two smaller side altars. New pews and Stations of the Cross were also added.'),
('standrewchurch', 'SL', 'Cerkev sv. Andreja', 'Nekoč slikovita majhna cerkev, prvič omenjena v dokumentu iz leta 1229, je postala veličastna župnijska cerkev, ki ponuja slikovit razgled na celotno območje Andraža nad Polzelo. Začetki te cerkve so povezani z lokalnimi zemljiškimi lastniki Polzele in grofi Celjskimi. Friderik I je upravljal Zgornjekranjski samostan, ki je imel posesti v bližini sv. Andreja in Dobriča. Cerkev sv. Andreja je bila sprva večja kapela, zgrajena v romanskem slogu. Danes ni ostankov ali vidnih znakov te kapele. V drugi polovici 15. stoletja je bila kapela obnovljena in razširjena v gotskem slogu. Ostanki iz tega obdobja so še danes vidni, najbolj zanimiv je gotski kamniti portal, ki je imel dva grba: malteški križ na desni in grb grofov Celjskih s tremi zvezdami na levi. Ta simbol kaže, da so imeli grofje Celjski in poveljniki Polzele patronat nad cerkvijo. Od leta 1545 je bila omenjena kot podružnica župnije Polzela. Sedanja cerkev vključuje prezbiterij, ladjo in dve stranski kapeli, ki ji dajejo obliko križa. V drugi polovici 19. stoletja je bila deležna večje prenove, ko so bili nameščeni novi oltarji: glavni oltar, dva večja in dva manjša stranska oltarja. Dodane so bile tudi nove klopi in postaje križevega pota.'),
('standrewchurch', 'DE', 'Kirche St. Andreas', 'Einst eine malerische kleine Kirche, die erstmals in einem Dokument von 1229 erwähnt wurde, ist sie inzwischen zu einer prächtigen Pfarrkirche geworden, die einen malerischen Blick auf das gesamte Gebiet von Andraž nad Polzelo bietet. Die Ursprünge dieser Kirche sind mit den lokalen Grundbesitzern von Polzela und den Grafen von Cilli verbunden. Friedrich I. verwaltete das Oberkrainer Kloster, das Besitzungen in der Nähe von St. Andreas und Dobrič hatte. Die Kirche St. Andreas war ursprünglich eine größere Kapelle, die im romanischen Stil erbaut wurde. Heute gibt es keine Überreste oder sichtbare Zeichen dieser Kapelle. In der zweiten Hälfte des 15. Jahrhunderts wurde die Kapelle im gotischen Stil umgebaut und erweitert. Überreste aus dieser Zeit sind noch heute sichtbar, wobei das interessanteste der gotische Steinportal ist, das zwei Wappen zeigt: das Malteserkreuz rechts und das Wappen der Grafen von Cilli mit drei Sternen links. Dieses Symbol zeigt, dass die Grafen von Cilli und die Kommandanten von Polzela die Patronage über die Kirche hatten. Seit 1545 wird sie als Filiale der Pfarrei Polzela erwähnt. Die heutige Kirche umfasst das Presbyterium, das Kirchenschiff und zwei Seitenkapellen, die ihr die Form eines Kreuzes verleihen. In der zweiten Hälfte des 19. Jahrhunderts wurde sie umfassend renoviert, wobei neue Altäre installiert wurden: der Hauptaltar, zwei größere und zwei kleinere Seitenaltäre. Es wurden auch neue Bänke und Kreuzwegstationen hinzugefügt.'),
('standrewchurch', 'NL', 'Kerk van St. Andreas', 'Ooit een schilderachtige kleine kerk, voor het eerst genoemd in een document uit 1229, is het inmiddels uitgegroeid tot een prachtige parochiekerk die een schilderachtig uitzicht biedt over het hele gebied van Andraž nad Polzelo. De oorsprong van deze kerk is verbonden met de lokale landeigenaren van Polzela en de graven van Celje. Frederik I beheerde het Opper-Krainse klooster, dat landgoederen had in de buurt van St. Andreas en Dobrič. De kerk van St. Andreas was oorspronkelijk een grotere kapel, gebouwd in de romaanse stijl. Vandaag zijn er geen overblijfselen of zichtbare tekenen van deze kapel. In de tweede helft van de 15e eeuw werd de kapel herbouwd en uitgebreid in de gotische stijl. Overblijfselen uit deze periode zijn nog steeds zichtbaar, met als meest interessante het gotische stenen portaal, dat twee wapenschilden toont: het Maltezer kruis rechts en het wapenschild van de graven van Celje met drie sterren links. Dit symbool geeft aan dat de graven van Celje en de commandanten van Polzela het patronaat over de kerk hadden. Sinds 1545 wordt het genoemd als een filiaal van de parochie Polzela. De huidige kerk omvat het priesterkoor, het schip en twee zijkapellen die het de vorm van een kruis geven. Het onderging een grote renovatie in de tweede helft van de 19e eeuw, waarbij nieuwe altaren werden geïnstalleerd: het hoofdaltaar, twee grotere en twee kleinere zijaltaren. Er werden ook nieuwe banken en kruiswegstaties toegevoegd.');

-- plaguememorial
INSERT INTO poi_translation (poi_key, lang, display_name, description) VALUES
('plaguememorial', 'EN', 'Plague Memorial in Dobrič', 'It is located in Dobrič, halfway between Podvin and Gora Oljka. It stands out from other landmarks because its base is a four-sided masonry tower. It was erected as a memorial to the plague or Black Death, which ravaged the area in the first half of the 17th century. Nearby is a depression, which according to tradition is the remnant of a collapsed pit where many locals who died from the plague were buried.'),
('plaguememorial', 'SL', 'Spomenik kužnim žrtvam v Dobriču', 'Spomenik kuge se nahaja v Dobriču, na pol poti med Podvinom in Goro Oljko. Izstopa med drugimi znamenitostmi zaradi svoje štiristranske zidane stolpne osnove. Postavljen je bil kot spomin na kugo ali črno smrt, ki je pustošila po tem območju v prvi polovici 17. stoletja. V bližini je depresija, ki je po tradiciji ostanek zrušene jame, kjer so pokopali številne domačine, ki so umrli zaradi kuge.'),
('plaguememorial', 'DE', 'Seuchenopferdenkmal in Dobrič', 'Das Pestdenkmal befindet sich in Dobrič, auf halbem Weg zwischen Podvin und Gora Oljka. Es hebt sich von anderen Sehenswürdigkeiten durch seine vierseitige gemauerte Turmbasis ab. Es wurde als Denkmal für die Pest oder den Schwarzen Tod errichtet, der das Gebiet in der ersten Hälfte des 17. Jahrhunderts verwüstete. In der Nähe befindet sich eine Vertiefung, die laut Tradition der Überrest einer eingestürzten Grube ist, in der viele Einheimische begraben wurden, die an der Pest gestorben sind.'),
('plaguememorial', 'NL', 'Pestmonument in Dobrič', 'Het pestmonument bevindt zich in Dobrič, halverwege tussen Podvin en Gora Oljka. Het valt op tussen andere bezienswaardigheden door zijn vierzijdige gemetselde torenbasis. Het werd opgericht als een gedenkteken voor de pest of de Zwarte Dood, die het gebied in de eerste helft van de 17e eeuw teisterde. In de buurt bevindt zich een depressie, die volgens de traditie de overblijfselen is van een ingestorte put waar veel lokale bewoners die aan de pest zijn overleden, werden begraven.');

-- mesicmill
INSERT INTO poi_translation (poi_key, lang, display_name, description) VALUES
('mesicmill', 'EN', 'Mešič Mill', 'Mešič Mill was one of the most famous mills in Polzela. On the estate, the Struga stream powered both the mill and a sawmill from 1923, and later also a dynamo for home lighting. After 1940, the mill was powered by a turbine with three sets of millstones. Before World War II, it primarily milled for locals and Polzela residents, and later for trade as well. The mill ceased operations in 1955. Mešič Mill is also notable for its architectural features, which have now been beautifully restored.'),
('mesicmill', 'SL', 'Mešičev mlin', 'Mešičev mlin je bil eden najbolj znanih mlinov v Polzeli. Na posestvu je potok Struga poganjal tako mlin kot žago od leta 1923, kasneje pa tudi dinamo za domačo razsvetljavo. Po letu 1940 je mlin poganjala turbina s tremi kompleti mlinskih kamnov. Pred drugo svetovno vojno je mlel predvsem za domačine in prebivalce Polzele, kasneje pa tudi za trgovino. Mlin je prenehal obratovati leta 1955. Mešičev mlin je znan tudi po svojih arhitekturnih značilnostih, ki so zdaj čudovito obnovljene.'),
('mesicmill', 'DE', 'Mešič Mühle', 'Die Mešič-Mühle war eine der bekanntesten Mühlen in Polzela. Auf dem Anwesen trieb der Struga-Bach sowohl die Mühle als auch ein Sägewerk ab 1923 an, später auch einen Dynamo für die Hausbeleuchtung. Nach 1940 wurde die Mühle von einer Turbine mit drei Mahlstein-Sets angetrieben. Vor dem Zweiten Weltkrieg mahlte sie hauptsächlich für Einheimische und Bewohner von Polzela, später auch für den Handel. Die Mühle stellte 1955 den Betrieb ein. Die Mešič-Mühle ist auch für ihre architektonischen Merkmale bekannt, die inzwischen wunderschön restauriert wurden.'),
('mesicmill', 'NL', 'Mešič Molen', 'Mešič-molen was een van de meest bekende molens in Polzela. Op het landgoed dreef de Struga-stroom zowel de molen als een zaagmolen vanaf 1923 aan, en later ook een dynamo voor huisverlichting. Na 1940 werd de molen aangedreven door een turbine met drie sets molenstenen. Voor de Tweede Wereldoorlog maalde het voornamelijk voor de lokale bevolking en inwoners van Polzela, en later ook voor de handel. De molen stopte met werken in 1955. Mešič-molen is ook opmerkelijk vanwege zijn architectonische kenmerken, die nu prachtig zijn gerestaureerd.');

-- riverloznica
INSERT INTO poi_translation (poi_key, lang, display_name, description) VALUES
('riverloznica', 'EN', 'River Ložnica and Its Floodplain', 'This area includes the wet and marshy meadows along the Ložnica River from Sp. Založ to Zalog in the Savinja Valley. The region, with numerous river meanders, riparian vegetation, flood meadows with moisture-loving vegetation (reed beds, alder groves, sedges), and remnants of lowland oak forests, creates a distinctive landscape and provides a habitat for numerous plant and animal species, including endangered animal species such as: birds - the common buzzard (Buteo buteo), common kestrel (Falco tinnunculus), Eurasian sparrowhawk (Accipiter nisus), grey heron (Ardea cinerea), common quail (Coturnix coturnix), grey-headed woodpecker (Picus canus), red-backed shrike (Lanius collurio), kingfisher (Alcedo atthis), common whitethroat (Sylvia communis), Eurasian nuthatch (Sitta europaea), Eurasian penduline tit (Remiz pendulinus), sedge warbler (Acrocephalus schoenobaenus); amphibians - common frog (Rana temporaria), agile frog (Rana dalmatina), common toad (Bufo bufo), alpine newt (Triturus alpestris), smooth newt (Triturus vulgaris), and green frog (Rana kl. esculenta).'),
('riverloznica', 'SL', 'Reka Ložnica in njena poplavna ravnica', 'To območje vključuje mokre in močvirne travnike ob reki Ložnici od Sp. Založa do Zaloga v Savinjski dolini. Regija, z številnimi rečnimi meandri, obrežno vegetacijo, poplavnimi travniki z vlago ljubečo vegetacijo (trstičje, jelševje, šaši) in ostanki nižinskih hrastovih gozdov, ustvarja značilno pokrajino in zagotavlja življenjski prostor številnim rastlinskim in živalskim vrstam, vključno z ogroženimi živalskimi vrstami, kot so: ptice - kanja (Buteo buteo), postovka (Falco tinnunculus), skobec (Accipiter nisus), siva čaplja (Ardea cinerea), prepelica (Coturnix coturnix), sivi detel (Picus canus), rdečeglavi srakoper (Lanius collurio), vodomec (Alcedo atthis), trstni cvrčalec (Sylvia communis), brglez (Sitta europaea), trstni cvrčalec (Remiz pendulinus), trstni cvrčalec (Acrocephalus schoenobaenus); dvoživke - navadna žaba (Rana temporaria), spretna žaba (Rana dalmatina), navadna krastača (Bufo bufo), planinski pupek (Triturus alpestris), gladki pupek (Triturus vulgaris) in zelena žaba (Rana kl. esculenta).'),
('riverloznica', 'DE', 'Fluss Ložnica und ihre Aue', 'Dieses Gebiet umfasst die feuchten und sumpfigen Wiesen entlang des Ložnica-Flusses von Sp. Založ bis Zalog im Savinja-Tal. Die Region, mit zahlreichen Flussmäandern, Ufervegetation, Überschwemmungswiesen mit feuchtigkeitsliebender Vegetation (Schilf, Erlenhaine, Seggen) und Resten von Tiefland-Eichenwäldern, schafft eine charakteristische Landschaft und bietet Lebensraum für zahlreiche Pflanzen- und Tierarten, einschließlich gefährdeter Tierarten wie: Vögel - Mäusebussard (Buteo buteo), Turmfalke (Falco tinnunculus), Sperber (Accipiter nisus), Graureiher (Ardea cinerea), Wachtel (Coturnix coturnix), Grauspecht (Picus canus), Neuntöter (Lanius collurio), Eisvogel (Alcedo atthis), Dorngrasmücke (Sylvia communis), Kleiber (Sitta europaea), Beutelmeise (Remiz pendulinus), Schilfrohrsänger (Acrocephalus schoenobaenus); Amphibien - Grasfrosch (Rana temporaria), Springfrosch (Rana dalmatina), Erdkröte (Bufo bufo), Alpenmolch (Triturus alpestris), Teichmolch (Triturus vulgaris) und Grünfrosch (Rana kl. esculenta).'),
('riverloznica', 'NL', 'Rivier Ložnica en zijn Overstromingsvlakte', 'Dit gebied omvat de natte en moerassige weiden langs de Ložnica-rivier van Sp. Založ tot Zalog in de Savinja-vallei. De regio, met talrijke riviermeanders, oevervegetatie, overstromingsweiden met vochtminnende vegetatie (rietvelden, elzenbossen, zegge), en resten van laagland-eikenbossen, creëert een kenmerkend landschap en biedt een habitat voor talrijke planten- en diersoorten, waaronder bedreigde diersoorten zoals: vogels - buizerd (Buteo buteo), torenvalk (Falco tinnunculus), sperwer (Accipiter nisus), blauwe reiger (Ardea cinerea), kwartel (Coturnix coturnix), grijsgekleurde specht (Picus canus), roodrugklauwier (Lanius collurio), ijsvogel (Alcedo atthis), grasmus (Sylvia communis), boomklever (Sitta europaea), baardman (Remiz pendulinus), rietzanger (Acrocephalus schoenobaenus); amfibieën - gewone kikker (Rana temporaria), behendige kikker (Rana dalmatina), gewone pad (Bufo bufo), alpenwatersalamander (Triturus alpestris), kleine watersalamander (Triturus vulgaris) en groene kikker (Rana kl. esculenta).');

-- =============================================================================
-- SEED: POI Images (derived from images/ directory listing)
-- =============================================================================

INSERT INTO poi_image (poi_key, image_path, sort_order) VALUES
('castle',            '/images/castle.webp',            0),
('castle',            '/images/castle1.webp',           1),
('castle',            '/images/castle2.webp',           2),
('castle',            '/images/castle3.webp',           3),
('park',              '/images/park.webp',              0),
('park',              '/images/park1.webp',             1),
('park',              '/images/park2.webp',             2),
('park',              '/images/park3.webp',             3),
('icecream',          '/images/icecream.webp',          0),
('icecream',          '/images/icecream1.webp',         1),
('icecream',          '/images/icecream2.webp',         2),
('fortesa',           '/images/fortesa.webp',           0),
('fortesa',           '/images/fortesa1.webp',          1),
('fortesa',           '/images/fortesa2.webp',          2),
('mountoljka',        '/images/mountoljka.webp',        0),
('mountoljka',        '/images/mountoljka1.webp',       1),
('mountoljka',        '/images/mountoljka2.webp',       2),
('mountoljka',        '/images/mountoljka3.webp',       3),
('maurerhouse',       '/images/maurerhouse.webp',       0),
('maurerhouse',       '/images/maurerhouse1.webp',      1),
('maurerhouse',       '/images/maurerhouse2.webp',      2),
('maurerhouse',       '/images/maurerhouse3.webp',      3),
('romancamp',         '/images/romancamp.webp',         0),
('romancamp',         '/images/romancamp1.webp',        1),
('romancamp',         '/images/romancamp2.webp',        2),
('tractormuseum',     '/images/tractormuseum.webp',     0),
('cajhnhayrack',      '/images/cajhnhayrack.webp',      0),
('clayfigurines',     '/images/clayfigurines.webp',     0),
('noviklostermanor',  '/images/noviklostermanor.webp',  0),
('stmargharetachurch','/images/stmargharetachurch.webp',0),
('stmargharetachurch','/images/stmargharetachurch1.webp',1),
('stnicholaschurch',  '/images/stnicholaschurch.webp',  0),
('stnicholaschurch',  '/images/stnicholaschurch1.webp', 1),
('stnicholaschurch',  '/images/stnicholaschurch2.webp', 2),
('standrewchurch',    '/images/standrewchurch.webp',    0),
('standrewchurch',    '/images/standrewchurch1.webp',   1),
('standrewchurch',    '/images/standrewchurch2.webp',   2),
('plaguememorial',    '/images/plaguememorial.webp',     0),
('mesicmill',         '/images/mesicmill.webp',         0),
('riverloznica',      '/images/riverloznica.webp',      0);

-- =============================================================================
-- SEED: UI Texts (welcome, takeme × 4 languages = 8 rows)
-- =============================================================================

INSERT INTO ui_text (text_key, lang, value) VALUES
('welcome', 'EN', 'Welcome to '),
('welcome', 'SL', 'Dobrodošli v '),
('welcome', 'DE', 'Willkommen in '),
('welcome', 'NL', 'Welkom in '),
('takeme',  'EN', 'Take me there!'),
('takeme',  'SL', 'Pelji me tja!'),
('takeme',  'DE', 'Nehmt mich dorthin!'),
('takeme',  'NL', 'Neem me daarheen!');

